/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example;

import java.io.IOException;

public class App {
    public static void main(final String[] args) throws IOException {
        TestJavaStackTrace.dumpStackTrace();
    }
}
