/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example;

import static org.junit.jupiter.api.Assertions.fail;

import java.io.IOException;

import org.junit.jupiter.api.Test;

class AppTest {
    @Test void appHasAGreeting() {
        try {
            TestJavaStackTrace.dumpStackTrace();
            fail("Should have thrown exception");
        } catch (final IOException e) {
            e.printStackTrace();
        }
    }
}
